import { GameMeta } from "@/types/game";

export const gamesRegistry: GameMeta[] = [
  {
    id: "tic-tac-toe",
    name: "Tic Tac Toe",
    description: "Classic 3×3 grid. Get three in a row to beat the computer — or a friend.",
    category: "strategy",
    icon: "Grid3x3",
    route: "/games/tic-tac-toe",
    difficulty: "easy",
    players: "1-2",
    status: "available",
  },
  {
    id: "memory",
    name: "Memory",
    description: "Flip cards and find matching pairs. Harder difficulties reveal a bigger grid.",
    category: "puzzle",
    icon: "LayoutGrid",
    route: "/games/memory",
    difficulty: "medium",
    players: "1",
    status: "available",
  },
  {
    id: "rock-paper-scissors",
    name: "Rock Paper Scissors",
    description: "Challenge the computer. Hard mode reads your patterns and counters them.",
    category: "quick",
    icon: "HandMetal",
    route: "/games/rock-paper-scissors",
    difficulty: "easy",
    players: "1",
    status: "available",
  },
  {
    id: "reaction-timer",
    name: "Reaction Timer",
    description: "Wait for green, then click as fast as you can. Test your raw reflexes.",
    category: "quick",
    icon: "Timer",
    route: "/games/reaction-timer",
    difficulty: "easy",
    players: "1",
    status: "available",
  },
  {
    id: "snake",
    name: "Snake",
    description: "Eat food to grow, don't crash into yourself or the walls. Speed scales with difficulty.",
    category: "arcade",
    icon: "Activity",
    route: "/games/snake",
    difficulty: "medium",
    players: "1",
    status: "available",
  },
  {
    id: "2048",
    name: "2048",
    description: "Slide and merge tiles to reach 2048. Hard mode spawns more 4-tiles.",
    category: "puzzle",
    icon: "Grid2X2",
    route: "/games/2048",
    difficulty: "hard",
    players: "1",
    status: "available",
  },
  {
    id: "pong",
    name: "Pong",
    description: "Classic table tennis. Move your paddle to beat the computer — first to 7 wins.",
    category: "arcade",
    icon: "Circle",
    route: "/games/pong",
    difficulty: "medium",
    players: "1-2",
    status: "available",
  },
  {
    id: "number-guessing",
    name: "Number Guessing",
    description: "Guess the hidden number. Hot/cold hints guide you. Fewer attempts on hard.",
    category: "quick",
    icon: "Hash",
    route: "/games/number-guessing",
    difficulty: "easy",
    players: "1",
    status: "available",
  },
  {
    id: "color-guess",
    name: "Color Guess",
    description: "Match the HEX colour to the right swatch. Options get closer on hard mode.",
    category: "quick",
    icon: "Palette",
    route: "/games/color-guess",
    difficulty: "medium",
    players: "1",
    status: "available",
  },
  {
    id: "whack-a-mole",
    name: "Whack-a-Mole",
    description: "Moles pop up fast — click them before they hide! Speed increases each difficulty.",
    category: "arcade",
    icon: "Target",
    route: "/games/whack-a-mole",
    difficulty: "medium",
    players: "1",
    status: "available",
  },
];
